<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>FreelaMatchAPI</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	</ItemGroup>

	<ItemGroup>
		<!-- Ignorar arquivos de cobertura -->
		<Compile Remove="coverage-results\**\*.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="3.2.0" />
		<PackageReference Include="FluentAssertions" Version="8.8.0" />
		<PackageReference Include="MailKit" Version="4.14.1" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.20" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.6" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.6" PrivateAssets="all" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.6" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
		<PackageReference Include="Moq" Version="4.20.72" />
		<PackageReference Include="NewRelic.Agent.Api" Version="10.47.0" />
		<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.14.0" />
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.14.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.14.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.14.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.14.0" />
		<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.2" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
		<PackageReference Include="xunit" Version="2.9.3" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
		<PackageReference Include="System.Text.Json" Version="8.0.5" />
	</ItemGroup>

</Project>
