sonar.projectKey=AnnaBLoz_freelamatch-api
sonar.organization=annabloz
sonar.host.url=https://sonarcloud.io

sonar.projectName=FreelaMatch
sonar.projectVersion=1.0

sonar.sources=freela-match-api
sonar.tests=freela-match-api-test

sonar.cs.opencover.reportsPaths=freela-match-api-test/TestResults/**/coverage.opencover.xml

sonar.exclusions=**/wwwroot/**,**/bin/**,**/obj/**
sonar.test.exclusions=**/*.cshtml

sonar.language=cs
