sonar.projectKey=SEU_PROJETO_KEY
sonar.organization=SEU_ORG
sonar.projectName=FreelaMatch-API

sonar.sourceEncoding=UTF-8

# Código fonte
sonar.sources=.

# Onde ficam os testes
sonar.tests=.

sonar.inclusions=**/*.cs
sonar.test.inclusions=**/*Tests.cs

# Para excluir migrations e arquivos de infra
sonar.exclusions=bin/**, obj/**, **/Migrations/**
