name: Analyze .NET Backend

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug final 
        run: |
          echo "=== Raiz do workspace ==="
          ls -la
          echo ""
          echo "=== Conteúdo da pasta FreelaMatchAPI ==="
          ls -la FreelaMatchAPI

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore, Build & Test com cobertura
        run: |
          dotnet restore FreelaMatchAPI/FreelaMatchAPI.csproj
          dotnet build FreelaMatchAPI/FreelaMatchAPI.csproj -c Release --no-restore
          dotnet test FreelaMatchAPI/FreelaMatchAPI.csproj \
            --no-build \
            -c Release \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=cobertura \
            /p:CoverletOutput=coverage.cobertura.xml \
            --logger "trx" \
            --results-directory TestResults

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=AnnaBLoz_freelamatch-api
            -Dsonar.organization=annabloz
            -Dsonar.cs.vstest.reportsPaths=**/TestResults/*.trx
            -Dsonar.cs.cobertura.reportPaths=coverage.cobertura.xml
            -Dsonar.qualitygate.wait=true